import { useState } from "react";
import { ApiError, api } from "../api/client";
import type { ExplainResponse } from "../api/types";

interface Props {
  indicatorKey: string;
  countries: string[];
}

// "Explain this chart" — calls the Claude-backed endpoint (Phase 3). Until that
// endpoint is deployed the call 404s and we show an honest placeholder.
export default function ExplainPanel({ indicatorKey, countries }: Props) {
  const [result, setResult] = useState<ExplainResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function run() {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      setResult(await api.explain(indicatorKey, countries));
    } catch (e) {
      if (e instanceof ApiError && e.status === 404) {
        setError("The plain-language explainer becomes available once the Claude endpoint is deployed (Phase 3).");
      } else {
        setError(e instanceof Error ? e.message : "Something went wrong.");
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="explain">
      <div className="explain-head">
        <div>
          <strong>Explain this chart</strong>
          <div style={{ fontSize: "0.84rem", color: "var(--muted)" }}>
            A plain-language summary for non-experts, generated by Claude.
          </div>
        </div>
        <button className="btn" onClick={run} disabled={loading}>
          {loading ? "Thinking…" : result ? "Regenerate" : "Explain"}
        </button>
      </div>

      {error && (
        <div className="explain-body" style={{ color: "var(--crisis-ink)" }}>
          {error}
        </div>
      )}
      {result && (
        <>
          <div className="explain-body">{result.summary}</div>
          <div className="explain-tag">
            {result.generated_by === "claude"
              ? `Generated by ${result.model}. AI summaries can be imperfect — verify against the source data.`
              : "Generated by a templated fallback (no AI key configured)."}
          </div>
        </>
      )}
    </div>
  );
}
